### PR TITLE
Added SM Insert Parameters Command

### PR DESCRIPTION
**Pull request by BoomShotKapow**
Hopefully this is useful in some way to you, it's nothing that exciting. I just really wanted it in the extension, so I went ahead and figured it out and implemented it.

Feel free to do whatever you want with it. I apologize if I didn't follow your formatting very well, I'm not used to the size 2 tabs (spaces).

### CODE REVIEW

**Comment by Sarrus1** [comment]
Looks good! No worries for the formatting, I use an auto-formatter anyways.

What do you think about a "snippet-like" feature where it would autofill the params and prompt you with the name of the variables only?

**Comment by BoomShotKapow** [comment]
> Looks good! No worries for the formatting, I use an auto-formatter anyways.
> 
> What do you think about a "snippet-like" feature where it would autofill the params and prompt you with the name of the variables only?

Sorry, I didn't notice your question. And that could be really nice, yea. As long as it's separate from the keybind for just flat out inserting the parameters as-is.

**Comment by Sarrus1** [comment]
@BoomShotKapow 
Not sure if this matches your use case perfectly, but in VSCode, if you type:
`RegAdminCmd()` (for example), then the signature providers shows up, then by pressing tab, you can spawn all the functions parameters on the line.

**Comment by DeathScore13** [comment]
how about adding automatic input mode without using ctrl+shift+i? 👀

**Comment by Sarrus1** [comment]
What I coul do is transform it into an autocompletion thing where, when you open the first `(` it would suggest an autocompletion which would insert all the parameters. I think that would work better than a fully automated tjing which could be frustrating.

**Pull request merged**
