### PR TITLE
Fix Formatting public and Plugin myinfo

### PR DESCRIPTION
**Pull request by DarklSide**

### CODE REVIEW

**Comment by DarklSide** [comment]
Image_1
Format Document:
Image_2

**Comment by Sarrus1** [comment]
Hello, thanks your for this, but I don't get it, your picture "Format Document" shows that this doesn't work,

```c
public Plugin myinfo =
    {
    name = "Test",
    author = "Test",
    description = "Test",
    version = "1.0.0", // "1.0.0.0",
    url = "Test"}
```

is not correct

**Comment by DarklSide** [comment]
Picture "Format Document" displays how it is currently formatting the document.
This fix correctly formats the document: "public Plugin myinfo", and removes the problem of lines 2 to 6.
Current format document:
Current format document
Fix format document:
Fix format document

**Comment by Sarrus1** [comment]
I have tested your code incorrectly, I don't know how.
This works great, I'm merging this.

Thanks again!

**Pull request merged**
